name: Architectural Decision Records
description: >
    A simple jekyll theme for recording software decisions with minimal styling.

master_repo: false
url: "https://bloomonkey.github.io/white-paper-adrs"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name: bloomonkey
  avatar:
  email:
  # Social networking links used in footer. Update and remove as you like.
  github: https://github.com/bloomonkey
  stackexchange:
  linkedin:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
